### ISSUE TITLE
Chrome Freezing

### ISSUE THREAD

**Issue by AkoreJepade** [StatiXOS/android_device_essential_mata#2]
Chrome, Chrome Beta and Edge (Chromium based) all three apps freeze and popup a message "Chrome isn't responding" 

Firefox works flawlessly which is very strange that Google's own browser will not work in Google's own OS but Firefox does.

Can you check into this?

Thank you very much.

Build number: RD1A.201105.003.C1

**Comment by anayw2001** [comment]
no one is reporting this issue anymore, and it's likely not a device issue anyway. closing.

**Comment by aamadorj** [comment]
I also reported this weird Chromium based browsers issue at the StatiXOS Telegram Official Chat a while ago and it's still happening with Brave Browser. The logcat I shared then is attached.

My PH-1 is running latest StatiXOS 4.1 build.

[logcat_Chromium_issue_mata.txt](https://github.com/StatiXOS/android_device_essential_mata/files/5992344/logcat_Chromium_issue_mata.txt)
