### ISSUE TITLE
Device won't charge sometimes (Snowcone 2021-12-20 build)

### ISSUE THREAD

**Issue by aamadorj** [StatiXOS/android_device_essential_mata#6]
Sometimes, device won't charge when connected and only a restart will fix this issue, as reported by some users at the [XDA thread](https://forum.xda-developers.com/t/rom-snowcone-mata-12-statixos-v5-0.4360385/) with StatiXOS Snowcone 2021-12-20 build. While this issue is happening, the battery settings show connected but not charging.

**Comment by aamadorj** [comment]
Somehow, the issue is gone. My guess is new Magisk (24.0) fixed the issue.

**Comment by aamadorj** [comment]
Well, the issue happened again. But now it's definitely less frequent.

**Comment by aamadorj** [comment]
I haven't seen the issue in a while. I guess it wasn't caused by the ROM.

**Comment by OJZen** [comment]
I had the same issue, but not frequently. It's charged super slowly, I can charge in shutdown when I got this trouble.
BTW, my phone had no root.

**Comment by aamadorj** [comment]
The issue is gone for good at my phone. It even was gone before I updated to newest StatixOS for mata, so my guess is the issue wasn't caused by the ROM.
